version: '3.9'
networks:
    local:
        name: local-network
services:
    mongo:
        container_name: 'mongo'
        image: mongo:latest
        volumes:
            - ./mongo-data/:/data/db/
        ports:
            - '27017:27017'
        networks:
            - local

    backend:
        container_name: 'backend'
        depends_on:
            - mongo
        volumes:
            - ./:/app/
            - ./node_modules/:/app/node_modules/
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=development
            - PORT=3000
            - MONGO_URI=mongodb://mongo:27017/gic
            - X_API_KEY=development
        image: 'backend'
        networks:
            - local

    frontend:
        container_name: 'frontend'
        depends_on:
            - backend
        volumes:
            - ./:/app/
            - ./node_modules/:/app/node_modules/
        ports:
            - '3001:3001'
        environment:
            - NODE_ENV=development
        image: 'frontend'
        networks:
            - local
